name: Github Pages

on: [push]

jobs:
  build_wasm:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: wasm-pack build
      - name: Archive wasm package
        uses: actions/upload-artifact@v3
        with:
          name: wasm
          path: pkg
  deploy:
    needs: build_wasm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download wasm package
        uses: actions/download-artifact@v3
        with:
          name: wasm
          path: pkg
      - run: npm install
        working-directory: www
      - run: npm run build
        working-directory: www
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: www/dist
